kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: aws-pvc-kuber
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ebs-gp3-with-encryption
  resources:
    requests:
      storage: 10Gi
