apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: api-token
  namespace: default
spec:
  refreshInterval: "0"
  # refreshInterval: "1m"
  secretStoreRef:
    name: aws-parameter-store
    kind: ClusterSecretStore
  target:
    name: k8s-secret-api-token
    creationPolicy: Owner
  data:
  - secretKey: token
    remoteRef:
      key: demo-api-token