---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: gitlab-runner-secret
  namespace: gitlab-space-external
spec:
  refreshInterval: "0"
  secretStoreRef:
    kind: ClusterSecretStore
    name: aws-parameter-store
  target:
    name: gitlab-runner-secret
    creationPolicy: Owner
    template:
      data:
        # DEPRECATED: The Registration Token(runner-registration-token) for adding new Runners to the GitLab Server.
        # ref: https://docs.gitlab.com/ee/ci/runners/new_creation_workflow.html
        runner-registration-token: "" # need to leave as an empty string for compatibility reasons
        runner-token: '{{ index . "runner-token" }}'
  data:
    - secretKey: runner-token
      remoteRef:
        key: demo-gitlab
        property: runner.tokens.external
