apiVersion: v1
kind: Pod
metadata:
  name: demo-pod
spec:
  containers:
    - name: container
      image: busybox
      command: [ "/bin/sh", "-c", "echo Interval = $(INTERVAL). Desired count of print = $(COUNT). Text: $(TEXT_ARG)"]
      env:
        - name: INTERVAL
          valueFrom:
            configMapKeyRef:
              name: demo-cm
              key: interval
        - name: COUNT
          valueFrom:
            configMapKeyRef:
              name: demo-cm
              key: count
        - name: TEXT_ARG
          valueFrom:
            configMapKeyRef:
              name: demo-cm
              key: config.ini
  restartPolicy: Never