apiVersion: v1
kind: Service
metadata:
  name: endpoints-service
spec:
  ports:
  - port: 80
---
apiVersion: v1
kind: Endpoints
metadata:
  name: endpoints-service
subsets:
  - addresses:
    - ip: 10.75.21.169
    - ip: 10.75.22.141
    ports:
    - port: 8000