apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: demo-app
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: development
  source:
    repoURL: {{ .Values.source.repoURL }}
    targetRevision: {{ .Values.source.targetRevision }}
    path: {{ .Values.source.path }}
    helm:
      values: |
        hosts:
          app1: {{ .Values.appHosts.app1 }}
          app2: {{ .Values.appHosts.app2 }}

        clusterIssuer:
          name: {{ .Values.clusterIssuer.name }}

  destination:
    namespace: {{ .Values.namespace }}
    server: {{ .Values.spec.destination.server }}

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
