apiVersion: v1
kind: Pod
metadata:
  name: app-kuber-with-labels
  labels: 
    environment: dev 
    app: http-server
spec:
  containers:
  - name: app-kuber-container
    image: bokovets/kuber:0.1
    ports:
    - containerPort: 8000

