apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: hello-suspend
spec:
  schedule: "*/1 * * * *"
  concurrencyPolicy: Allow
  successfulJobsHistoryLimit: 2
  failedJobsHistoryLimit: 2
  suspend: false
  jobTemplate:
    spec:
      backoffLimit: 1
      template:
        spec:
          containers:
          - name: hello
            image: busybox
            args:
            - /bin/sh
            - -c
            - date; echo "Hello World!"; exit $((RANDOM%2))
          restartPolicy: OnFailure
