apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: cronjon-startingdeadlineseconds
spec:
  schedule: "*/5 * * * *"
  startingDeadlineSeconds: 60
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: hello
            image: busybox
            args:
            - /bin/sh
            - -c
            - date; echo "Hello World!"; sleep 340
          restartPolicy: Never