apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: app-3-cert
spec:
  secretName: app-tls-3
  dnsNames:
    - app-3.kubxr.com
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer