apiVersion: v1
kind: Service
metadata:
  name: kuber-service-nodeport
spec:
  externalTrafficPolicy: Local
  # sessionAffinity: ClientIP
  selector:
    app: http-server
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
      nodePort: 30080 # port-range: 30000-32767
  type: NodePort

