# https://docs.gitlab.com/charts/advanced/external-object-storage/aws-iam-roles.html
# https://docs.gitlab.com/ee/install/aws/manual_install_aws.html
---
apiVersion: v1
kind: Secret
metadata:
  name: gitlab-rails-s3-storage
  namespace: gitlab
stringData:
  connection: |
    provider: AWS
    use_iam_profile: true
    region: eu-west-1
---
apiVersion: v1
kind: Secret
metadata:
  name: s3-credentials
  namespace: gitlab
stringData:
  config: |
    [default]
    bucket_location = eu-west-1
