apiVersion: apps/v1
kind: Deployment
metadata:
  name: kuber-tcp
  labels:
    app: kuber
spec:
  replicas: 1
  selector:
    matchLabels:
      app: http-server-tcp
  template:
    metadata:
      labels:
        app: http-server-tcp
    spec:
      containers:
        - name: kuber-app
          image: bakavets/kuber:v1.0
          ports:
            - containerPort: 8000
          livenessProbe:
            tcpSocket:
              port: 8000
            initialDelaySeconds: 15 # Defaults to 0 seconds. Minimum value is 0.
            periodSeconds: 10 # Default to 10 seconds. Minimum value is 1.
            timeoutSeconds: 1 # Defaults to 1 second. Minimum value is 1.
            successThreshold: 1 # Defaults to 1. Must be 1 for liveness and startup Probes. Minimum value is 1.
            failureThreshold: 3 # Defaults to 3. Minimum value is 1.
---
apiVersion: v1
kind: Service
metadata:
  name: kuber-service-tcp
spec:
  selector:
    app: http-server-tcp
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
      nodePort: 30002
  type: NodePort
