apiVersion: apps/v1
kind: Deployment
metadata:
  name: kuber-default
  namespace: default
  labels:
    app: kuber
spec:
  replicas: 1
  selector:
    matchLabels:
      app: http-server-default
  template:
    metadata:
      labels:
        app: http-server-default
    spec:
      containers:
      - name: kuber-app
        image: bakavets/kuber:v1.0
        ports:
        - containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: kuber-default-service
  namespace: default
spec:
  selector:
    app: http-server-default
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
