apiVersion: apps/v1
kind: Deployment
metadata:
  name: kuber-args
  labels:
    app: kuber
spec:
  replicas: 1
  selector:
    matchLabels:
      app: http-server-args
  template:
    metadata:
      labels:
        app: http-server-args
    spec:
      containers:
      - name: kuber-app
        image: bakavets/kuber:v1.0-args
        args: ["$(INTERVAL)","$(COUNT)","$(TEXT_ARG)"]
        ports:
        - containerPort: 8000
        env:
        - name: INTERVAL
          value: "3"
        - name: COUNT
          value: "4"
        - name: TEXT_ARG
          value: "Interval = $(INTERVAL). Desired count of print = $(COUNT)."

