apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: result
  name: result
  namespace: vote
spec:
  replicas: 1
  selector:
    matchLabels:
      app: result
  template:
    metadata:
      labels:
        app: result
    spec:
      containers:
        - image: ghcr.io/bretfisher/example-voting-app-result:gha-1638605336
          name: result
          ports:
            - containerPort: 80
              name: result
