apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: gitlab-agent
  namespace: gitlab-agent
spec:
  refreshInterval: "0"
  secretStoreRef:
    kind: ClusterSecretStore
    name: aws-parameter-store
  target:
    name: gitlab-agent
    creationPolicy: Owner
  data:
    - secretKey: token
      remoteRef:
        key: demo-gitlab
        property: kas.tokens.internal
