---
apiVersion: v1
kind: Namespace
metadata:
  name: example-3
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kuber
  namespace: example-3
  labels:
    app: kuber
spec:
  replicas: 1
  selector:
    matchLabels:
      app: http-server
  template:
    metadata:
      labels:
        app: http-server
    spec:
      serviceAccountName: app-sa-3
      containers:
        - name: kuber-app
          image: bakavets/kuber
          ports:
            - containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: kuber-service
  namespace: example-3
spec:
  selector:
    app: http-server
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
