apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: gitlab-pages-wildcard-cert
  namespace: gitlab
spec:
  secretName: gitlab-pages-tls-wildcard
  dnsNames:
    - gitlab-pg.kubxr.com
    - '*.gitlab-pg.kubxr.com'
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
