apiVersion: apps/v1
kind: Deployment
metadata:
  name: with-prefer-no-schedule-taint
  labels:
    app: kuber
spec:
  replicas: 4
  selector:
    matchLabels:
      app: http-server
  template:
    metadata:
      labels:
        app: http-server
    spec:
      containers:
        - name: kuber-app
          image: bakavets/kuber
          ports:
            - containerPort: 8000
          resources:
            limits:
              cpu: 1
              memory: 2Gi
            requests:
              cpu: 1
              memory: 512Mi
      tolerations:
        - key: node.k8s/app-role
          operator: Exists
          effect: PreferNoSchedule
