apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: mysql-secrets
  namespace: example
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: SecretStore
    name: aws-ps-ns
  target:
    name: mysql-secrets
    creationPolicy: Owner
  data:
  - secretKey: MYSQL_USER
    remoteRef:
      key: demo-mysql
      property: MYSQL_USER
  - secretKey: MYSQL_PASSWORD
    remoteRef:
      key: demo-mysql
      property: MYSQL_PASSWORD
