# https://kubernetes.io/docs/reference/kubernetes-api/config-and-storage-resources/storage-class-v1/
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: custom-gp2
provisioner: kubernetes.io/aws-ebs # https://kubernetes.io/docs/concepts/storage/storage-classes/#provisioner
parameters:
  type: gp2
reclaimPolicy: Retain # https://kubernetes.io/docs/concepts/storage/storage-classes/#reclaim-policy
allowVolumeExpansion: true
