apiVersion: external-secrets.io/v1beta1
kind: ClusterExternalSecret
metadata:
  name: demo-common-secret
spec:
  # The name to be used on the ExternalSecrets
  externalSecretName: demo-common-secret

  # This is a basic label selector to select the namespaces to deploy ExternalSecrets to.
  # you can read more about them here https://kubernetes.io/docs/concepts/overview/working-with-objects/labels/#resources-that-support-set-based-requirements
  namespaceSelector:
    matchLabels:
      demo: my-secret

  # How often the ClusterExternalSecret should reconcile itself
  # This will decide how often to check and make sure that the ExternalSecrets exist in the matching namespaces
  refreshTime: "1m"

  # This is the spec of the ExternalSecrets to be created
  # The content of this was taken from our ExternalSecret example
  externalSecretSpec:
    secretStoreRef:
      name: aws-parameter-store
      kind: ClusterSecretStore

    refreshInterval: "1h"
    target:
      name: demo-common
      creationPolicy: Owner

    data:
    - secretKey: DEMO
      remoteRef:
        key: demo-mysql
        property: name.last
