apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: wildcard-cert
spec:
  secretName: tls-wildcard
  dnsNames:
  - kubxr.com
  - '*.kubxr.com'
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer