---
name: 01 Basic Docker Build
# simplest workflow possible


# Each file if its own workflow
# workflow contains jobs

on:
  push:
    branches:
      - main
  pull_request:

# Here we
jobs:
  build-image:
    name: Build Image
    runs-on: ubuntu-latest
    steps:
      # login to Github
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # and then building and possibly pushing to github
      - name: Docker build
        uses: docker/build-push-action@v4
        with:
          push: ${{ github.event_name != 'pull_request' }}
          tags: bretfisher/docker-ci-automation:latest,bretfisher/docker-ci-automation:01
