apiVersion: v1
kind: ServiceAccount
metadata:
  name: app-sa-2
  namespace: example-2
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  # "namespace" omitted since ClusterRoles are not namespaced
  name: example-2-cr
rules:
  - apiGroups: ["apps"]
    resources: ["deployments"]
    verbs: ["list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: example-2-crb
subjects:
  - kind: ServiceAccount
    name: app-sa-2
    namespace: example-2
roleRef:
  kind: ClusterRole
  name: example-2-cr
  apiGroup: rbac.authorization.k8s.io
