apiVersion: apps/v1
kind: Deployment
metadata:
  name: zone-spread-topology
  labels:
    app: kuber
spec:
  replicas: 6
  selector:
    matchLabels:
      app: http-server
  template:
    metadata:
      labels:
        app: http-server
    spec:
      containers:
        - name: kuber-app
          image: nginx
      topologySpreadConstraints:
        - maxSkew: 1
          topologyKey: topology.kubernetes.io/zone
          whenUnsatisfiable: DoNotSchedule
          labelSelector:
            matchLabels:
              app: http-server
          # matchLabelKeys:
          #   - app
          #   - pod-template-hash
