apiVersion: apps/v1
kind: Deployment
metadata:
  name: with-node-selector
  labels:
    app: kuber
spec:
  replicas: 3
  selector:
    matchLabels:
      app: http-server
  template:
    metadata:
      labels:
        app: http-server
    spec:
      containers:
        - name: kuber-app
          image: bakavets/kuber
          ports:
            - containerPort: 8000
      nodeSelector:
        topology.kubernetes.io/zone: eu-west-1b
        capacityType: spot
