.PHONY: clean All

All:
	@echo "----------Building project:[ MPG - Debug ]----------"
	@cd "DivideByZero" && "$(MAKE)" -f  "MPG.mk"
clean:
	@echo "----------Cleaning project:[ MPG - Debug ]----------"
	@cd "DivideByZero" && "$(MAKE)" -f  "MPG.mk" clean
