apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: hello-allow
spec:
  schedule: "*/1 * * * *"
  concurrencyPolicy: Allow
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: hello
            image: busybox
            args:
            - /bin/sh
            - -c
            - date; echo "Hello World!"; sleep 140
          restartPolicy: OnFailure
