apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: hello-without-startingdeadlineseconds
spec:
  schedule: "*/1 * * * *"
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      backoffLimit: 1
      template:
        spec:
          containers:
          - name: hello
            image: busybox
            args:
            - /bin/sh
            - -c
            - date; echo "Hello World!"; sleep 7000
          restartPolicy: Never
