apiVersion: batch/v1
kind: Job
metadata:
  name: pi-parallelism-completions
spec:
  parallelism: 3
  completions: 7
  backoffLimit: 4
  template:
    spec:
      containers:
      - name: pi
        image: perl
        command: ["perl",  "-Mbignum=bpi", "-wle", "print bpi(2000)"]
      restartPolicy: Never