gitlabUrl: https://gitlab.com/
concurrent: 10
checkInterval: 3
logLevel: info

rbac:
  create: true
  clusterWideAccess: false
  rules:
    - resources: ["configmaps", "events", "pods", "pods/attach", "pods/exec", "secrets", "services"]
      verbs: ["get", "list", "watch", "create", "patch", "update", "delete"]
    - apiGroups: [""]
      resources: ["pods/exec"]
      verbs: ["create", "patch", "delete"]

metrics:
  enabled: true
  portName: metrics
  port: 9252
  serviceMonitor:
    enabled: false

runners:
  config: |
    [[runners]]
      [runners.kubernetes]
        namespace = "{{.Release.Namespace}}"
        image = "ubuntu:22.04"
        service_account_overwrite_allowed = "ci-.*"
        node_selector_overwrite_allowed = "karpenter.sh/capacity-type=.*"

        # https://docs.gitlab.com/runner/executors/kubernetes.html#configuration-settings
        
        # build container
        cpu_request = "100m"
        memory_request = "100Mi"
        cpu_limit = "1"
        memory_limit = "1Gi"
        
        cpu_request_overwrite_max_allowed = "3"
        memory_request_overwrite_max_allowed = "12Gi"
        cpu_limit_overwrite_max_allowed =  "3600m"
        memory_limit_overwrite_max_allowed = "14Gi"
        
        # service containers
        service_cpu_request = "50m"
        service_memory_request = "128Mi"
        service_cpu_limit = "1"
        service_memory_limit = "1Gi"

        # helper container
        helper_cpu_request = "50m"
        helper_memory_request = "64Mi"
        helper_cpu_limit = "500m"
        helper_memory_limit = "128Mi"

      [runners.kubernetes.node_selector]
        # "node.k8s/role" = "gitlab-runner"
        "eks.amazonaws.com/capacityType"="ON_DEMAND"
      [runners.kubernetes.node_tolerations]
        "node.k8s/gitlab-role=runner" = "NoSchedule"

  executor: kubernetes
  secret: gitlab-runner-secret

resources:
  limits:
    memory: 256Mi
    cpu: 200m
  requests:
    memory: 128Mi
    cpu: 100m